version: '3'
services:
  backend:
    build: ./
    ports:
      - 3000:3000
    networks:
      - purrlinq-app
    depends_on:
      - mongo
      - rabbitMq
    environment:
      CLOUDAMQP_URL: amqp://guest:guest@rabbitmq:5672
      MONGO_CONNECTION_STRING: mongodb://mongo:27017/brokenlink
      CLIENT_APP_URL: https://rainbow-pie-78bf5e.netlify.app
      linkLimit: 100
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run build'
    volumes:
      - .:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - purrlinq-app
    volumes:
      - mongo-data:/data/db
  rabbitMq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - purrlinq-app
    volumes:
      - mongo-data:/data/db
networks:
  purrlinq-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
